version: '3.5'
services:
  consul:
    image: consul
    command: consul agent -dev -ui -client 0.0.0.0
    networks: 
      - realityNetwork
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:

networks: 
  realityNetwork:
    name: realityNetwork