export enum Unternehmen {
  'Accenture Dienstleistungen GmbH',
  'adesso AG',
  'Aleri Solutions Gmbh',
  'ARITHNEA GmbH',
  'Bayer AG',
  'Bertrandt',
  'Brockhaus AG',
  'Capgemini Deutschland GmbH',
  'CDI Concepts Development',
  'CEMA GmbH',
  'CHECK24 Vergleichsportal GmbH',
  'com2m GmbH',
  'Comline AG',
  'Continentale Versicherungsverbund',
  'Crosscan GmbH',
  'Deutsche Telekom AG',
  'DextraData GmbH',
  'e- Spirit AG',
  'EscrypT GmbH',
  'Fakultaet für Informatik',
  'Ferchau GmbH',
  'G Data Software AG',
  'HSBC Trinkaus & Burkhardt AG',
  'Huawei Deutschland',
  'img.ly',
  'ISD Software & Systeme GmbH',
  'itemis AG',
  'itestra GmbH',
  'Kassenaerztliche Vereinigung Westfalen-Lippe',
  'Knipp Medien und Kommunikation GmbH',
  'Materna I&C SE',
  'mindsquare GmbH',
  'Modis GmbH',
  'MotionMiners GmbH',
  'msg Systems AG',
  'Networkers AG',
  'Open Knowledge GmbH',
  'otris software AG',
  'Pixelboxx GmbH',
  'Quinscape GmbH',
  'real.digital',
  'REMONDIS IT Services GmbH & Co. KG',
  'Rhenus Office Logistics',
  'Robert Bosch GmbH',
  'Schleupen AG',
  'SCISYS',
  'Setlog GmbH',
  'shopware AG',
  'SOPTIM AG',
  'SSI Schaefer IT Solutions GmbH',
  'Swyx Solutions GmbH',
  'Tata Consultancy Services Deutschland GmbH',
  'TEDi GmbH & Co. KG',
  'UNIQ GmbH',
  'Vanderlande Industries GmbH',
  'viadee IT-Unternehmensberatung AG',
  'VISUS Health IT GmbH',
  'VMRay GmbH',
  'W3L AG',
  'Zalando SE'
}
