export enum Unternehmen {
  'Accenture',
  'adesso AG',
  'adesso mobile solutions GmbH',
  'All for One Steeb AG',
  'ALMATO GmbH',
  'Andrena Objects',
  'ARITHNEA GmbH',
  'AutoForm Engineering Deutschland GmbH',
  'Beschaffungsamt des Bundesministeriums des Innern',
  'BROCKHAUS AG',
  'BSI Business Systems Integration Deutschland GmbH',
  'Capgemini',
  'CAS Concepts and Solutions AG',
  'CDI Concepts Development Integration AG',
  'CEMA GmbH Spezialisten für Informationstechnolgie',
  'CHECK24 Vergleichsportal',
  'com2m GmbH',
  'Comline AG',
  'Conciso',
  'Continentale Versicherungsverbund',
  'Crosscan GmbH',
  'e-Spirit AG',
  'FERCHAU Engineering GmbH',
  'Fiducia & GAD IT AG',
  'FINCON Unternehmensberatung GmbH',
  'G DATA Software AG',
  'IFASEC GmbH',
  'itemis AG',
  'itestra GmbH',
  'Kassenärztliche Vereinigung Westfalen-Lippe',
  'Knipp Medien und Kommunikation GmbH',
  'Materna GmbH',
  'MEGLA GmbH',
  'mindsquare GmbH',
  'msg systems ag',
  'Networkers AG',
  'Open-Xchange GmbH',
  'OpusCapita Software GmbH',
  'PSI Software AG',
  'real,- Digital Payment & Technology Services GmbH',
  'RIPS Technologies GmbH',
  'SCISYS Deutschland GmbH',
  'Setlog GmbH',
  'shopware AG',
  'Sollers Consulting GmbH',
  'SSI Schäfer Noell GmbH',
  'Swyx Solutions AG',
  'Tata Consultancy Services Deutschland GmbH',
  'Techniker Krankenkasse',
  'TRILUX Group Management GmbH',
  'UNIQ GmbH (Urlaubsguru)',
  'valantic IT Group GmbH',
  'Vanderlande Industries GmbH',
  'viadee Unternehmensberatung GmbH',
  'Viega Holding GmbH & Co. KG',
  'VMRay GmbH',
  'W3L AG',
  'Zalando SE'
}
